### ISSUE TITLE
Feature request: transforms

### ISSUE THREAD

**Issue by msoler75** [francescolorenzetti/types-4-strapi#12] opened 2022-04-18 16:31 UTC
Thank for this generator.

I'm moving to strapi 4 and I'm using this strapi plugin: 
[Transformer Plugin](https://market.strapi.io/plugins/strapi-plugin-transformer)

So each item received by api is normally like:

```
{ 
  id,
  attributes:  {
    name, 
    description
  } 
}
```

and with this plugin the data is like the v3 strapi version (and better for me)

```
{ 
   id,
   name,
   description 
}
```

But the generator don't apply this transformation.

I ask if it may be that this option can be configured in the generation of the types.

Thanks!

**Comment by francescolorenzetti** [comment] 2022-04-19 09:36
Duplicate of #6

**Closed as completed by francescolorenzetti** 2022-04-19 09:36 UTC
